### ISSUE TITLE
Submit helpful python scripts

### ISSUE THREAD

**Issue by Abhishek627** [Abhishek627/bits#1]
Add python scripts which can help users in general development or eases some command they use on a regular basis.

Happy coding !!

**Comment by yashqwerty1** [comment]
@Abhishek627 Can you assign this to me so I can work on it.

**Comment by Rishav0907** [comment]
can i go for it?

**Comment by Abhishek627** [comment]
you guys can refer this issue in your PR. @Rishav0907 @yashqwerty1
