### ISSUE TITLE
Submit helpful python scripts

### ISSUE THREAD

**Issue by Abhishek627** [Abhishek627/bits#6]
Add python scripts which can act as reference to people who are new to that library. Please add comments in code explaining what this script does , the required version of import dependencies if any.

**Comment by Abhishek627** [comment]
@Rishav0907 I'll assign this to you

**Comment by prateekjaindev** [comment]
Can I add some monitoring scripts..??

**Comment by Abhishek627** [comment]
@prateekjaindev Sure. Please add appropriate folder like monitoring or devops and commit to that please.
