### ISSUE TITLE
Submit helpful python scripts- 3

### ISSUE THREAD

**Issue by Abhishek627** [Abhishek627/bits#7]
Add python scripts which can act as reference to people who are new to that library. Please add comments in code explaining what this script does , the required version of import dependencies if any.

**Comment by Abhishek627** [comment]
@yashqwerty1 I'll assign this to you. please create a PR referencing this issue.

**Comment by parzuko** [comment]
Can i not take this ?

**Comment by Abhishek627** [comment]
@parzuko assigned it to you. please reference this issue in you PR.

**Comment by cryp73r** [comment]
Please review #12 , may be you will find useful and interesting.
